import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/widgets/Nav/ui/Nav'
import { cn } from '@/shared/lib/utils'
import NavMobile from '@/widgets/Nav/ui/NavMobile'
import { detectMobileServer } from '@/shared/lib/DetectMobileServer'
import styles from './mainPage.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal
}: {
  children: React.ReactNode,
  modal: React.ReactNode
}) {
  
  const isMobile = detectMobileServer()
  const height = isMobile ? styles.navHeightMobile : styles.navHeight
  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-zinc-100 overflow-x-hidden', height)}>
        {isMobile ? <NavMobile /> : <Nav />}
          {children}
          {modal}
      </body>
    </html>
  )
}
