import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/widgets/Nav/ui/Nav'
import { cn } from '@/shared/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal
}: {
  children: React.ReactNode,
  modal: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'bg-zinc-100 overflow-x-hidden')}>
        <Nav />
        <main className='max-w-7xl m-auto'>
          {children}
        </main>
        {modal}
      </body>
    </html>
  )
}
